export const subCategoryTranslate = {
  "T-Shirt": "Áo thun",
  Shirt: "Áo sơ mi",
  Polo: "Áo polo",
  Hoodie: "Áo hoodie",
  Sweater: "Áo len",
  Jacket: "Áo khoác",
  Blazer: "Áo vest",
  "Tank Top": "Áo ba lỗ",
  "Crop Top": "Áo lửng",
  Coat: "Áo choàng",
  "Trench Coat": "Áo măng tô",
  Windbreaker: "Áo gió",
  "Bomber Jacket": "Áo bomber",
  "Denim Jacket": "Áo bò",
  Jeans: "Quần jeans",
  Trousers: "Quần dài",
  Shorts: "Quần short",
  Skirt: "Váy",
  Leggings: "Quần legging",
  Joggers: "Quần jogger",
  Dress: "Đầm",
  Jumpsuit: "Đồ liền thân",
  Overalls: "Yếm",
  Sneakers: "Giày thể thao",
  Loafers: "Giày lười",
  Boots: "Bốt",
  Sandals: "Dép sandal",
  Heels: "Giày cao gót",
  Hat: "Mũ",
  Cap: "Nón lưỡi trai",
  Belt: "Thắt lưng",
  Scarf: "Khăn choàng",
  Gloves: "Găng tay",
  Bag: "Túi xách",
  Sunglasses: "Kính râm",
  Watch: "Đồng hồ",
  Jewelry: "Trang sức",
  Underwear: "Đồ lót",
  Tracksuit: "Đồ thể thao",
  Sportswear: "Trang phục thể thao",
  Sleepwear: "Đồ ngủ",
  Swimwear: "Đồ bơi",
};
export const mainCategoryTranslate = {
  Topwear: "Áo",
  Bottomwear: "Quần",
  OnePiece: "Đồ liền thân",
  Footwear: "Giày dép",
  Accessories: "Phụ kiện",
  Underwear: "Đồ lót",
  Sportswear: "Đồ thể thao",
  Sleepwear: "Đồ ngủ",
  Swimwear: "Đồ bơi",
};
