export const translationMap = {
  gender: {
    nam: "Men",
    nữ: "Women",
    unisex: "Unisex",
    trẻ: "Kids",
    "trẻ em": "Kids",
  },
  mainCategory: {
    "áo trên": "Topwear",
    "quần dưới": "Bottomwear",
    "đồ liền thân": "OnePiece",
    "giày dép": "Footwear",
    "phụ kiện": "Accessories",
    "đồ lót": "Underwear",
    "đồ thể thao": "Sportswear",
    "đồ ngủ": "Sleepwear",
    "đồ bơi": "Swimwear",
  },
  subCategory: {
    "áo thun": "T-Shirt",
    áo: "Shirt",
    "áo polo": "Polo",
    "áo hoodie": "Hoodie",
    "áo len": "Sweater",
    "áo khoác": "Jacket",
    blazer: "Blazer",
    "áo ba lỗ": "Tank Top",
    "áo croptop": "Crop Top",
    "áo măng tô": "Coat",
    "áo khoác măng tô": "Trench Coat",
    "áo chống gió": "Windbreaker",
    "áo bomber": "Bomber Jacket",
    "áo khoác denim": "Denim Jacket",
    "quần jeans": "Jeans",
    "quần dài": "Trousers",
    "quần ngắn": "Shorts",
    váy: "Skirt",
    "quần legging": "Leggings",
    "quần jogger": "Joggers",
    đầm: "Dress",
    "đồ liền thân": "Jumpsuit",
    "quần yếm": "Overalls",
    "giày thể thao": "Sneakers",
    "giày lười": "Loafers",
    bốt: "Boots",
    sandal: "Sandals",
    "giày cao gót": "Heels",
    mũ: "Hat",
    "nón lưỡi trai": "Cap",
    "dây nịt": "Belt",
    khăn: "Scarf",
    "găng tay": "Gloves",
    túi: "Bag",
    "kính râm": "Sunglasses",
    "đồng hồ": "Watch",
    "trang sức": "Jewelry",
    "đồ lót": "Underwear",
    "bộ đồ thể thao": "Tracksuit",
    "đồ thể thao": "Sportswear",
    "đồ ngủ": "Sleepwear",
    "đồ bơi": "Swimwear",
  },
};
